workflows:
  android-release:
    name: FF Tournament APK Build
    environment:
      flutter: "stable" # or specific version like "3.13.0"
      android_signing:
        - keystore: FF_KEYSTORE
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
