workflows:
  android-release:
    name: Firebase Tournament Build
    environment:
      flutter: stable
      android_signing:
        - keystore: FF_KEYSTORE
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
